/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/japanese_house.glb -o src/components/JapaneseHouse.tsx -t -k --types 
Author: Daniel Stringer (https://sketchfab.com/DanielStringer)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/japanese-house-771899f2af8a4b57aa98b1ca1ae83034
Title: Japanese House
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Glass_Glass_0: THREE.Mesh;
    JapaneseHouse_House_0: THREE.Mesh;
  };
  materials: {
    Glass: THREE.MeshPhysicalMaterial;
    House: THREE.MeshStandardMaterial;
  };
};

type JapaneseHouseProps = JSX.IntrinsicElements["group"] & {
  castShadow?: boolean;
  receiveShadow?: boolean;
};

export function JapaneseHouse({
  castShadow = true,
  receiveShadow = true,
  ...props
}: JapaneseHouseProps) {
  const { nodes, materials } = useGLTF(
    "/models/japanese_house.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <group name="00afc5f36fa2451b8e70976350ccb5fafbx" scale={0.01}>
        <group
          name="Glass"
          position={[-199.339, 0, -301.235]}
          rotation={[-Math.PI / 2, 0, -Math.PI]}
        >
          <mesh
            name="Glass_Glass_0"
            geometry={nodes.Glass_Glass_0.geometry}
            material={materials.Glass}
            position={[0, 55.256, 0]}
            castShadow={castShadow}
            receiveShadow={receiveShadow}
          />
        </group>
        <group
          name="JapaneseHouse"
          position={[0.023, 0, -9.397]}
          rotation={[-Math.PI / 2, 0, -Math.PI / 2]}
        >
          <mesh
            name="JapaneseHouse_House_0"
            geometry={nodes.JapaneseHouse_House_0.geometry}
            material={materials.House}
            position={[-92.508, -344.106, 0]}
            castShadow={castShadow}
            receiveShadow={receiveShadow}
          />
        </group>
      </group>
    </group>
  );
}

useGLTF.preload("/models/japanese_house.glb");
