import { useControls } from "leva";

/**
 * SimonDevGrass12Controls - Extracted Leva Controls for Grass System
 *
 * This component contains all the Leva controls that were previously
 * embedded in SimonDevGrass11. This separation makes the main component
 * much cleaner and easier to debug.
 */
export const useSimonDevGrass12Controls = () => {
  const {
    grassCount,
    enableDynamicChunks,
    chunkSize,
    baseColor,
    middleColor,
    tipColor,
    gradientPower,
    baseTransitionPoint,
    tipTransitionPoint,
    maxDistance,
    highDetailDistance,
    mediumDetailDistance,
    disableLighting,
    specularIntensity,
    specularColor,
    specularPower,
    windStrength,
    windSpeed,
    windFrequency,
    windAmplitude,
    windTurbulence,
    flappingIntensity,
    grassHeightMultiplier,
    grassScaleMultiplier,
    windDirectionX,
    windDirectionZ,
    grassDensity,
    shadowCasting,
    shadowReceiving,
    alphaTest,
    disableMoonReflection,
    moonIntensity,
    moonDirectionX,
    moonDirectionY,
    moonDirectionZ,
    moonColor,
    disableTextureTint,
    edgeDarkeningStrength,
    textureRepeatX,
    textureRepeatY,
    sssIntensity,
    sssPower,
    sssScale,
    sssColor,
    disableSSS,
    contactShadowIntensity,
    contactShadowRadius,
    enableAO,
    aoIntensity,
    aoRadius,
    enableColorVariation,
    colorVariationIntensity,
    tipColorVariationIntensity,
    enableEnvMap,
    envMapIntensity,
    environmentType,
    roughnessBase,
    roughnessTip,
    fresnelPower,
    roughnessIntensity,
    enableDistanceFog,
    fogScatterDensity,
    fogExtinctionDensity,
    fogSkyColor,
    enableWrappedLighting,
    wrapAmount,
    enablePlayerInteraction,
    playerInteractionRadius,
    playerInteractionStrength,
    playerInteractionRepel,
    grassBaseWidth,
    grassTipWidth,
    grassBaseLean,
    enableAnisotropy,
    anisotropyStrength,
    anisotropyTangent,
    anisotropyBitangent,
    shadowAlphaThreshold,
    enableViewThickening,
    enableWind,
    bladesPerCluster,
    sunDirectionX,
    sunDirectionY,
    sunDirectionZ,
    bladeCurveAmount,
    widthTaperPower,
    tipPointPercent,
  } = useControls("SimonDev Grass 12 (Custom Shadows)", {
    grassCount: {
      value: 10000,
      min: 1000,
      max: 300000,
      step: 1000,
      label: "🌾 Grass Count",
    },
    bladesPerCluster: {
      value: 3,
      min: 1,
      max: 3,
      step: 1,
      label: "🌿 Blades Per Cluster (1=Single, 3=Clump)",
    },
    enableDynamicChunks: {
      value: false,
      label: "📦 Enable Dynamic Chunks (Disable for Static Testing)",
    },
    chunkSize: {
      value: 20,
      min: 10,
      max: 50,
      step: 5,
      label: "Chunk Size (optimization)",
    },
    baseColor: { value: "#2d5016" },
    middleColor: { value: "#51b770" },
    tipColor: { value: "#fff900" },
    gradientPower: { value: 1.0, min: 0.1, max: 3.0, step: 0.1 },
    baseTransitionPoint: { value: 0.1, min: 0.0, max: 0.5, step: 0.01 },
    tipTransitionPoint: { value: 0.6, min: 0.3, max: 0.9, step: 0.01 },
    maxDistance: {
      value: 100,
      min: 20,
      max: 200,
      step: 10,
      label: "🎯 Grass Radius (Distance from Player)",
    },
    highDetailDistance: {
      value: 60,
      min: 10,
      max: 100,
      step: 5,
      label: "High Quality Radius (Grass Around Player)",
    },
    mediumDetailDistance: {
      value: 100,
      min: 30,
      max: 150,
      step: 5,
      label: "Medium Quality Radius",
    },
    disableLighting: { value: false },
    specularIntensity: {
      value: 1.2,
      min: 0,
      max: 5,
      step: 0.1,
      label: "✨ Specular Intensity (Both Sun & Moon Glints)",
    },
    specularColor: {
      value: "#ffffff",
      label: "☀️ Sun Glint Color (Change to Debug/Test)",
    },
    specularPower: {
      value: 96,
      min: 8,
      max: 256,
      step: 8,
      label: "Specular Sharpness (Higher = Tighter Highlights)",
    },
    sunDirectionX: {
      value: 15.0,
      min: -50.0,
      max: 50.0,
      step: 1.0,
      label: "☀️ Sun Direction X",
    },
    sunDirectionY: {
      value: 25.0,
      min: 5.0,
      max: 50.0,
      step: 1.0,
      label: "☀️ Sun Direction Y (Height)",
    },
    sunDirectionZ: {
      value: 10.0,
      min: -50.0,
      max: 50.0,
      step: 1.0,
      label: "☀️ Sun Direction Z",
    },
    enableViewThickening: {
      value: true,
      label: "👁️ View-Space Thickening (Fuller, Tip-Protected ✅)",
    },
    enableWind: {
      value: false,
      label: "💨 Enable Wind Animation",
    },
    windStrength: { value: 1.0, min: 0.0, max: 2.0, step: 0.1 },
    windSpeed: { value: 1.0, min: 0.1, max: 3.0, step: 0.1 },
    windFrequency: { value: 0.1, min: 0.01, max: 0.5, step: 0.01 },
    windAmplitude: { value: 1.0, min: 0.0, max: 2.0, step: 0.1 },
    windTurbulence: { value: 1.0, min: 0.1, max: 2.0, step: 0.1 },
    flappingIntensity: { value: 1.0, min: 0.0, max: 3.0, step: 0.1 },
    grassHeightMultiplier: { value: 1.0, min: 0.5, max: 2.0, step: 0.1 },
    grassScaleMultiplier: { value: 0.7, min: 0.5, max: 2.0, step: 0.1 },
    windDirectionX: { value: 1.0, min: -2.0, max: 2.0, step: 0.1 },
    windDirectionZ: { value: 0.5, min: -2.0, max: 2.0, step: 0.1 },
    grassDensity: { value: 1.0, min: 0.1, max: 3.0, step: 0.1 },
    shadowCasting: { value: true },
    shadowReceiving: { value: true },
    alphaTest: { value: 0.1, min: 0.0, max: 1.0, step: 0.01 },
    shadowAlphaThreshold: {
      value: 0.5,
      min: 0.1,
      max: 1.0,
      step: 0.05,
      label: "🌑 Shadow Alpha Cutoff (Higher = Sharper Shadows)",
    },
    disableMoonReflection: {
      value: true,
      label: "🌙 Disable Moon Light (2nd Specular Source)",
    },
    moonIntensity: {
      value: 1.0,
      min: 0.0,
      max: 5.0,
      step: 0.1,
      label: "🌙 Moon Intensity (Multiplier for Moon Only)",
    },
    moonDirectionX: { value: -15.0, min: -50.0, max: 50.0, step: 5.0 },
    moonDirectionY: { value: 25.0, min: 10.0, max: 50.0, step: 5.0 },
    moonDirectionZ: { value: 10.0, min: -50.0, max: 50.0, step: 5.0 },
    moonColor: {
      value: "#ff0000",
      label: "🌙 Moon Highlight Color (Try Red/Blue/White)",
    },
    disableTextureTint: {
      value: true,
      label: "🚫 Disable Edge Darkening (Texture Gradient)",
    },
    edgeDarkeningStrength: {
      value: 0.3,
      min: 0.0,
      max: 1.0,
      step: 0.05,
      label: "🎚️ Edge Darkening Strength (0=Off, 0.3=Subtle, 1=Full)",
    },
    textureRepeatX: { value: 1.0, min: 0.1, max: 5.0, step: 0.1 },
    textureRepeatY: { value: 1.0, min: 0.1, max: 5.0, step: 0.1 },
    sssIntensity: { value: 0.8, min: 0.0, max: 3.0, step: 0.1 },
    sssPower: { value: 1.5, min: 0.5, max: 5.0, step: 0.1 },
    sssScale: { value: 2.0, min: 0.1, max: 5.0, step: 0.1 },
    sssColor: { value: "#8fbc8f" },
    disableSSS: { value: true },
    contactShadowIntensity: { value: 0.0, min: 0.0, max: 1.0 },
    contactShadowRadius: { value: 2.0, min: 0.1, max: 10.0 },
    enableAO: { value: true },
    aoIntensity: { value: 1.0, min: 0.0, max: 2.0, step: 0.1 },
    aoRadius: { value: 0.1, min: 0.01, max: 1.0, step: 0.01 },
    enableColorVariation: { value: false },
    colorVariationIntensity: { value: 1.0, min: 0.0, max: 2.0, step: 0.1 },
    tipColorVariationIntensity: { value: 1.0, min: 0.0, max: 2.0, step: 0.1 },
    enableEnvMap: {
      value: false,
      label: "🌍 Enable IBL + Sky Reflections (Recommended!)",
    },
    envMapIntensity: {
      value: 1.0,
      min: 0.0,
      max: 3.0,
      step: 0.1,
      label: "🌍 IBL Strength (Sky Ambient + Tip Reflections)",
    },
    environmentType: {
      value: "industrial_sunset",
      options: ["industrial_sunset", "kloofendal", "qwantani"],
      label: "🌅 Environment HDR (Controls Sky Color/Ambient)",
    },
    roughnessBase: {
      value: 0.15,
      min: 0.0,
      max: 1.0,
      step: 0.05,
      label: "💎 Roughness Base (0=Wet/Shiny, 1=Dry/Matte)",
    },
    roughnessTip: {
      value: 0.02,
      min: 0.0,
      max: 1.0,
      step: 0.01,
      label: "✨ Roughness Tip (Lower = More Sky Reflection)",
    },
    fresnelPower: {
      value: 3.0,
      min: 1.0,
      max: 10.0,
      step: 0.5,
      label: "💎 Fresnel Power (Sky Reflection at Edges)",
    },
    roughnessIntensity: {
      value: 1.0,
      min: 0.0,
      max: 2.0,
      step: 0.1,
      label: "🎚️ Roughness Multiplier (Global Roughness Scale)",
    },
    environmentType: {
      value: "industrial_sunset",
      options: ["industrial_sunset", "kloofendal", "qwantani"],
      label: "🌅 Environment HDR (Controls Sky Color/Ambient)",
    },
    enableDistanceFog: {
      value: false,
      label: "🌫️ Enable Distance Fog (Quick_Grass Style)",
    },
    fogScatterDensity: {
      value: 0.001,
      min: 0.0,
      max: 0.01,
      step: 0.0001,
      label: "💨 Fog Scatter Density (Light Spread) - Higher = More Fog",
    },
    fogExtinctionDensity: {
      value: 0.005,
      min: 0.0,
      max: 0.02,
      step: 0.0001,
      label: "🌫️ Fog Extinction Density (Object Darkening) - Higher = Darker",
    },
    fogSkyColor: {
      value: "#c8d5e8",
      label: "☁️ Fog Sky Color (Fallback if EnvMap Off)",
    },
    enableWrappedLighting: {
      value: true,
      label: "💡 Enable Wrapped Lighting (Softer, Fuller Grass)",
    },
    wrapAmount: {
      value: 0.5,
      min: 0.0,
      max: 1.0,
      step: 0.05,
      label: "🌀 Wrap Amount (0.5=Balanced, Higher=Softer)",
    },
    enablePlayerInteraction: {
      value: true,
      label: "🏃 Enable Player Interaction (Grass Bends When You Walk!)",
    },
    playerInteractionRadius: {
      value: 2.5,
      min: 0.5,
      max: 10.0,
      step: 0.5,
      label: "📍 Player Interaction Radius (Distance Grass Bends)",
    },
    playerInteractionStrength: {
      value: 0.3,
      min: 0.0,
      max: 1.0,
      step: 0.05,
      label: "💪 Player Interaction Strength (How Much Grass Bends)",
    },
    playerInteractionRepel: {
      value: true,
      label: "🔄 Repel Mode (ON=Bend Away, OFF=Attract/Magnet)",
    },
    grassBaseWidth: {
      value: 0.15,
      min: 0.05,
      max: 0.5,
      step: 0.01,
      label: "🌾 Grass Base Width (0.15=Natural, 0.3=Thick)",
    },
    grassTipWidth: {
      value: 0.06,
      min: 0.02,
      max: 0.3,
      step: 0.01,
      label: "🌾 Grass Tip Width (0.03=Sharp, 0.06=Natural, 0.12=Rounded)",
    },
    grassBaseLean: {
      value: 0.0,
      min: 0.0,
      max: 0.6,
      step: 0.05,
      label: "🌿 Forward Lean (0=Straight, 0.2=Natural, 0.4=Heavy)",
    },
    bladeCurveAmount: {
      value: 0.0,
      min: 0.0,
      max: 0.8,
      step: 0.05,
      label: "🌊 Blade S-Curve (0=Straight, 0.2=Natural, 0.5=Curved)",
    },
    widthTaperPower: {
      value: 2.0,
      min: 0.5,
      max: 4.0,
      step: 0.1,
      label: "📐 Width Taper Power (Higher = Sharper Taper)",
    },
    tipPointPercent: {
      value: 0.05,
      min: 0.01,
      max: 0.3,
      step: 0.01,
      label: "▲ Tip Point Length (0.03=Sharp, 0.05=Natural, 0.1=Long)",
    },
    enableAnisotropy: { value: false },
    anisotropyStrength: { value: 0.8, min: 0.0, max: 2.0, step: 0.1 },
    anisotropyTangent: { value: 3.0, min: 0.1, max: 8.0, step: 0.1 },
    anisotropyBitangent: { value: 0.2, min: 0.05, max: 2.0, step: 0.05 },
  });

  return {
    grassCount,
    enableDynamicChunks,
    chunkSize,
    baseColor,
    middleColor,
    tipColor,
    gradientPower,
    baseTransitionPoint,
    tipTransitionPoint,
    maxDistance,
    highDetailDistance,
    mediumDetailDistance,
    disableLighting,
    specularIntensity,
    specularColor,
    specularPower,
    windStrength,
    windSpeed,
    windFrequency,
    windAmplitude,
    windTurbulence,
    flappingIntensity,
    grassHeightMultiplier,
    grassScaleMultiplier,
    windDirectionX,
    windDirectionZ,
    grassDensity,
    shadowCasting,
    shadowReceiving,
    alphaTest,
    disableMoonReflection,
    moonIntensity,
    moonDirectionX,
    moonDirectionY,
    moonDirectionZ,
    moonColor,
    disableTextureTint,
    edgeDarkeningStrength,
    textureRepeatX,
    textureRepeatY,
    sssIntensity,
    sssPower,
    sssScale,
    sssColor,
    disableSSS,
    contactShadowIntensity,
    contactShadowRadius,
    enableAO,
    aoIntensity,
    aoRadius,
    enableColorVariation,
    colorVariationIntensity,
    tipColorVariationIntensity,
    enableEnvMap,
    envMapIntensity,
    environmentType,
    roughnessBase,
    roughnessTip,
    fresnelPower,
    roughnessIntensity,
    enableDistanceFog,
    fogScatterDensity,
    fogExtinctionDensity,
    fogSkyColor,
    enableWrappedLighting,
    wrapAmount,
    enablePlayerInteraction,
    playerInteractionRadius,
    playerInteractionStrength,
    playerInteractionRepel,
    grassBaseWidth,
    grassTipWidth,
    grassBaseLean,
    enableAnisotropy,
    anisotropyStrength,
    anisotropyTangent,
    anisotropyBitangent,
    shadowAlphaThreshold,
    enableViewThickening,
    enableWind,
    bladesPerCluster,
    sunDirectionX,
    sunDirectionY,
    sunDirectionZ,
    bladeCurveAmount,
    widthTaperPower,
    tipPointPercent,
  };
};

export default useSimonDevGrass12Controls;
