/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/low_poly_flower-transformed.glb -o src/components/models/Flower.tsx --types 
Author: beepbopghh (https://sketchfab.com/beepbopghh)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/low-poly-flower-e7553892ef3b4114bd0e510a6dc91d49
Title: Low Poly Flower
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    stem_0: THREE.Mesh;
  };
  materials: {
    Material: THREE.MeshBasicMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/low_poly_flower-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.stem_0.geometry}
        material={materials.Material}
        position={[0, 0, 0]}
        rotation={[0, 0, 0]}
        scale={0.463}
      />
    </group>
  );
}

useGLTF.preload("/low_poly_flower-transformed.glb");
