/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/stone-origin-transformed.glb -o src/components/models/Stone.tsx --types 
*/

import * as THREE from "three";
import React from "react";
import { useGLTF } from "@react-three/drei";
import { GLTF } from "three-stdlib";

type GLTFResult = GLTF & {
  nodes: {
    Rock_H_01_Rock_H_01_Material_0: THREE.Mesh;
  };
  materials: {
    Rock_H_01_Material: THREE.MeshStandardMaterial;
  };
  animations: GLTFAction[];
};

export function Model(props: JSX.IntrinsicElements["group"]) {
  const { nodes, materials } = useGLTF(
    "/stone-origin-transformed.glb"
  ) as GLTFResult;
  return (
    <group {...props} dispose={null}>
      <mesh
        geometry={nodes.Rock_H_01_Rock_H_01_Material_0.geometry}
        material={materials.Rock_H_01_Material}
        position={[0, 0, 0]}
        rotation={[0, 0, 0]}
        scale={100}
      />
    </group>
  );
}

useGLTF.preload("/stone-origin-transformed.glb");
